# Этап 1: Сборка
FROM maven:3.9.6-eclipse-temurin-17-alpine AS build
WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn clean package -DskipTests


RUN find . -type f -name "*.jar" \
    | grep "target/" \
    | grep -v "sources" \
    | grep -v "javadoc" \
    | grep -v "original" \
    | head -n 1 \
    | xargs -I {} cp {} /app/app.jar

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring

COPY --from=build /app/app.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
