FROM node:20-alpine AS frontend
WORKDIR /frontend


COPY digital-bookshelf/package*.json ./

RUN npm ci

COPY digital-bookshelf/ .

ARG REACT_API_URL=/api/v1
RUN echo "VITE_API_URL=${REACT_API_URL}" > .env

RUN npm run build


FROM maven:3.9.6-eclipse-temurin-17-alpine AS build
WORKDIR /app

COPY diplom/pom.xml .
COPY diplom/src ./src


COPY --from=frontend /frontend/dist ./src/main/resources/static


RUN mvn clean package -DskipTests


RUN find . -type f -name "*.jar" \
    | grep "target/" \
    | grep -v "sources" \
    | grep -v "javadoc" \
    | grep -v "original" \
    | head -n 1 \
    | xargs -I {} cp {} /app/app.jar



FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring

COPY --from=build /app/app.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
